# Generated by Django 5.1 on 2024-08-28 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loggs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Loggs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "logg",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="loggs.logg"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "loggs",
            },
        ),
    ]
