# Generated by Django 5.1 on 2024-08-28 15:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("loggs", "0002_loggs"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="loggs",
            options={"verbose_name_plural": "logs"},
        ),
    ]
