# Generated by Django 5.1 on 2024-08-28 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loggs", "0003_alter_loggs_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loggs",
            name="logg",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="loggs.logg",
            ),
        ),
    ]
